import * as THREE from 'three';
import { positionAt } from './path.js';

// Ten grave markers flanking the church approach, alternating sides so the
// walk reads as an avenue. They carried carved song titles when the credits
// lived in the world; the catalog now lives in the panels at the altar, so
// these are set dressing and nothing more. Nothing here imports CREDITS, and
// sceneManager passes a hardcoded creditCount — the sole surviving link is a
// test asserting one stone per credit, so adding or removing a credit means
// adding or removing a row below, while retitling one costs nothing.
// Deterministic — the clearance test below is only
// meaningful against fixed positions.
// Generated by sampling the road between t=0.12 and t=0.56 and stepping a
// perpendicular offset of ~4.6-5.4m alternately to each side, then measured
// at 4.60m clearance from the camera corridor.
export const MONUMENT_SPOTS = [
  [5.6, 39.93, 0.13, 1.0],
  [-3.46, 35.72, -0.44, 1.1],
  [7.18, 33.98, 0.23, 0.95],
  [-2.75, 30.97, -0.26, 1.05],
  [6.32, 26.81, 0.54, 1.0],
  [-4.45, 27.24, 0.06, 1.1],
  [3.86, 21.05, 0.67, 0.95],
  [-6.17, 21.24, -0.06, 1.05],
  [3.81, 17.82, 0.2, 1.0],
  [-5.16, 12.93, -0.66, 1.1],
];

function minDistanceToRoute(x, z) {
  let min = Infinity;
  for (let i = 0; i <= 300; i++) {
    const p = positionAt(i / 300);
    const d = Math.hypot(p.x - x, p.z - z);
    if (d < min) min = d;
  }
  return min;
}


// Smallest horizontal distance from any monument to the scenic route — the
// camera must not clip a headstone as it walks the row.
export function minWorkPathClearance() {
  return Math.min(...MONUMENT_SPOTS.map(([x, z]) => minDistanceToRoute(x, z)));
}


// Which side of the scenic route a point falls on: positive one way,
// negative the other. Used to prove the stones flank the walk.
export function sideOfRoute(x, z) {
  let bestT = 0;
  let bestD = Infinity;
  for (let i = 0; i <= 300; i++) {
    const t = i / 300;
    const p = positionAt(t);
    const d = Math.hypot(p.x - x, p.z - z);
    if (d < bestD) { bestD = d; bestT = t; }
  }
  const p = positionAt(bestT);
  // Finite-difference tangent — avoids exporting yet another curve accessor
  // from path.js for one geometric test.
  const ahead = positionAt(Math.min(bestT + 0.01, 1));
  const behind = positionAt(Math.max(bestT - 0.01, 0));
  const tx = ahead.x - behind.x;
  const tz = ahead.z - behind.z;
  return tx * (z - p.z) - tz * (x - p.x);
}

const STONE_HEIGHT = 1.35;

function fallbackStone() {
  const g = new THREE.Group();
  const mat = new THREE.MeshStandardMaterial({ color: '#3a3f3a', roughness: 1 });
  const slab = new THREE.Mesh(new THREE.BoxGeometry(0.8, STONE_HEIGHT, 0.2), mat);
  slab.position.y = STONE_HEIGHT / 2;
  g.add(slab);
  return g;
}

// Scale an object so it stands `height` tall with its feet on y = 0.
function standUpright(obj, height) {
  const box = new THREE.Box3().setFromObject(obj);
  const size = box.getSize(new THREE.Vector3());
  if (size.y > 0) obj.scale.multiplyScalar(height / size.y);
  const after = new THREE.Box3().setFromObject(obj);
  const centre = after.getCenter(new THREE.Vector3());
  obj.position.x -= centre.x;
  obj.position.z -= centre.z;
  obj.position.y -= after.min.y;
  const wrapper = new THREE.Group();
  wrapper.add(obj);
  return wrapper;
}

export function buildMonuments({ scene, stonesGltf, creditCount }) {

  // The supplied GLB holds one mesh per marker, so each credit gets a
  // visually distinct stone. If it is missing we fall back to plain slabs —
  // the credits are DOM labels, so the information survives regardless.
  const sources = [];
  if (stonesGltf) {
    stonesGltf.scene.traverse((o) => { if (o.isMesh) sources.push(o); });
  }

  const credits = [];
  const count = Math.min(creditCount, MONUMENT_SPOTS.length);
  for (let i = 0; i < count; i++) {
    const [x, z, rotY, s] = MONUMENT_SPOTS[i];
    const src = sources.length ? sources[i % sources.length].clone(true) : fallbackStone();
    const stone = standUpright(src, STONE_HEIGHT * s);
    stone.position.set(x, 0, z);
    stone.rotation.y = rotY;
    scene.add(stone);
    credits.push(new THREE.Vector3(x, STONE_HEIGHT * s + 0.45, z));

  }

  return {};
}
