import * as THREE from 'three';
import { positionAt, targetAt, tNearest, FORK } from './path.js';
import { makeEngravedTexture, ENGRAVED_INK } from './engraving.js';
import { CREDITS } from '../content/portfolio.js';

// Ten markers flanking the monument row on the long swamp road, alternating
// sides so the walk reads as an avenue. Deterministic — the clearance test
// below is only meaningful against fixed positions.
// Not hand-guessed: generated by sampling the work curve across the row span
// (ROW_START -> ROW_END, ~40m) and stepping a perpendicular offset of about
// 3.2m alternately to each side. Measured afterwards at 3.01m clearance from
// the road, well outside the 1.4m camera corridor.
export const MONUMENT_SPOTS = [
  [27.4, 23.42, -1.12, 1.0],
  [29.8, 16.25, -1.73, 1.1],
  [34.18, 23.17, -1.14, 0.95],
  [36.66, 15.7, -1.75, 1.05],
  [40.79, 22.03, -1.17, 1.0],
  [43.41, 14.27, -1.77, 1.1],
  [47.51, 20.99, -1.17, 0.95],
  [50.23, 13.91, -1.78, 1.05],
  [54.05, 21.18, -1.25, 1.0],
  [57.21, 13.99, -1.82, 1.1],
];

function minDistanceToRoute(x, z, route) {
  let min = Infinity;
  for (let i = 0; i <= 300; i++) {
    const p = positionAt(i / 300, route);
    const d = Math.hypot(p.x - x, p.z - z);
    if (d < min) min = d;
  }
  return min;
}

// Exported wrapper so callers (tests included) can check clearance for an
// arbitrary point — e.g. the signpost — without duplicating the sampling
// loop above.
export function minDistanceToRouteFor(x, z, route) {
  return minDistanceToRoute(x, z, route);
}

// Measured against the parked camera, not eyeballed. The journey stops at
// the fork (camera ~(0.09, 1.80, 24.03), travelling toward lower z), so a
// sign standing level with or behind that point is out of frame exactly
// when it needs to be read. This spot sits ~6m ahead and to the left:
// 16.4 degrees off the camera's centre line, with 2.12m clearance from the
// direct road and 5.91m from the scenic one.
export const SIGNPOST_SPOT = [-3.64, 19.19];

// Turned to face the parked camera, so the boards present their faces
// rather than their edges at the moment of the choice.
export const SIGNPOST_ROT_Y = 0.66;

// Smallest horizontal distance from any monument to the scenic route — the
// camera must not clip a headstone as it walks the row.
export function minWorkPathClearance() {
  return Math.min(...MONUMENT_SPOTS.map(([x, z]) => minDistanceToRoute(x, z, 'work')));
}

// ...and how far the row sits from the main path, which is what makes the
// detour worth taking rather than something you can read from the road.
export function minDirectPathDistance() {
  return Math.min(...MONUMENT_SPOTS.map(([x, z]) => minDistanceToRoute(x, z, 'direct')));
}

// Angle between the parked camera's forward direction and the direction to
// the sign. The test above uses this to guarantee the sign is on screen.
export function signViewAngleDeg() {
  const tFork = tNearest(FORK, 'direct');
  const cam = positionAt(tFork, 'direct');
  const look = targetAt(tFork, 'direct');
  const fx = look.x - cam.x;
  const fz = look.z - cam.z;
  const fLen = Math.hypot(fx, fz);
  const [sx, sz] = SIGNPOST_SPOT;
  const vx = sx - cam.x;
  const vz = sz - cam.z;
  const vLen = Math.hypot(vx, vz);
  const cos = (fx * vx + fz * vz) / (fLen * vLen);
  return (Math.acos(Math.min(1, Math.max(-1, cos))) * 180) / Math.PI;
}

// Which side of the scenic route a point falls on: positive one way,
// negative the other. Used to prove the stones flank the walk.
export function sideOfRoute(x, z) {
  let bestT = 0;
  let bestD = Infinity;
  for (let i = 0; i <= 300; i++) {
    const t = i / 300;
    const p = positionAt(t, 'work');
    const d = Math.hypot(p.x - x, p.z - z);
    if (d < bestD) { bestD = d; bestT = t; }
  }
  const p = positionAt(bestT, 'work');
  // Finite-difference tangent — avoids exporting yet another curve accessor
  // from path.js for one geometric test.
  const ahead = positionAt(Math.min(bestT + 0.01, 1), 'work');
  const behind = positionAt(Math.max(bestT - 0.01, 0), 'work');
  const tx = ahead.x - behind.x;
  const tz = ahead.z - behind.z;
  return tx * (z - p.z) - tz * (x - p.x);
}

const STONE_HEIGHT = 1.35;

function fallbackStone() {
  const g = new THREE.Group();
  const mat = new THREE.MeshStandardMaterial({ color: '#3a3f3a', roughness: 1 });
  const slab = new THREE.Mesh(new THREE.BoxGeometry(0.8, STONE_HEIGHT, 0.2), mat);
  slab.position.y = STONE_HEIGHT / 2;
  g.add(slab);
  return g;
}

// Scale an object so it stands `height` tall with its feet on y = 0.
function standUpright(obj, height) {
  const box = new THREE.Box3().setFromObject(obj);
  const size = box.getSize(new THREE.Vector3());
  if (size.y > 0) obj.scale.multiplyScalar(height / size.y);
  const after = new THREE.Box3().setFromObject(obj);
  const centre = after.getCenter(new THREE.Vector3());
  obj.position.x -= centre.x;
  obj.position.z -= centre.z;
  obj.position.y -= after.min.y;
  const wrapper = new THREE.Group();
  wrapper.add(obj);
  return wrapper;
}

// A weathered two-armed signpost, built from primitives so there is no asset
// to hunt down and nothing to mis-scale. The arms carry engraved text planes
// (see engraving.js) tagged with the route each one selects.
function buildSignpost(scene) {
  const group = new THREE.Group();
  const wood = new THREE.MeshStandardMaterial({ color: '#241d16', roughness: 0.95 });

  const post = new THREE.Mesh(new THREE.CylinderGeometry(0.09, 0.11, 2.6, 7), wood);
  post.position.y = 1.3;
  group.add(post);

  const armGeo = new THREE.BoxGeometry(1.5, 0.26, 0.06);

  // A thin plane sitting a hair proud of the board's front face. Separating
  // the letters from the board means the wording can change without
  // touching geometry, and hover can tint the words alone.
  function carve(arm, text, route) {
    const tex = makeEngravedTexture(text);
    const plane = new THREE.Mesh(
      new THREE.PlaneGeometry(1.38, 0.22),
      new THREE.MeshBasicMaterial({
        map: tex,
        transparent: true,
        color: ENGRAVED_INK,
        depthWrite: false,
      }),
    );
    plane.position.z = 0.032; // just clear of the board's +z face
    arm.add(plane);
    arm.userData.route = route;
    arm.userData.textMesh = plane;
    return arm;
  }

  const beatsArm = carve(new THREE.Mesh(armGeo, wood), 'the beats', 'direct');
  beatsArm.position.set(-0.62, 2.25, 0);
  beatsArm.rotation.z = 0.04;
  const workArm = carve(new THREE.Mesh(armGeo, wood), 'the work', 'work');
  workArm.position.set(0.62, 1.85, 0);
  workArm.rotation.z = -0.05;
  group.add(beatsArm, workArm);

  // Stand it beside the road on the outside of the fork, angled to face the
  // walker. Offsetting the other way would put the post inside the work
  // route's turn (measured 0.72m clearance) -- the camera would clip it.
  // Measured clearance here: 2.67m from the work route, 3.00m from the
  // direct route, both comfortably outside the 1.4m corridor the monument
  // stones are held to.
  const [SIGN_X, SIGN_Z] = SIGNPOST_SPOT;
  group.position.set(SIGN_X, 0, SIGN_Z);
  group.rotation.y = SIGNPOST_ROT_Y;
  scene.add(group);

  const anchor = new THREE.Vector3(SIGN_X, 2.55, SIGN_Z);
  return { group, anchor, arms: [beatsArm, workArm] };
}

function buildCrypt(scene) {
  const group = new THREE.Group();
  const stone = new THREE.MeshStandardMaterial({ color: '#2b2b28', roughness: 1 });

  const body = new THREE.Mesh(new THREE.BoxGeometry(3.4, 2.8, 3.0), stone);
  body.position.y = 1.4;
  const roof = new THREE.Mesh(new THREE.ConeGeometry(2.7, 1.1, 4), stone);
  roof.position.y = 3.35;
  roof.rotation.y = Math.PI / 4;
  const doorway = new THREE.Mesh(
    new THREE.BoxGeometry(1.0, 1.9, 0.12),
    new THREE.MeshStandardMaterial({ color: '#0b0b0a', roughness: 1 }),
  );
  doorway.position.set(0, 0.95, 1.51);
  group.add(body, roof, doorway);

  // Just past the far end of the monument row, set back from the route so
  // the camera sweeps by its face rather than through it.
  group.position.set(22.5, 0, 8.5);
  group.rotation.y = -1.15;
  scene.add(group);

  return { group, anchor: new THREE.Vector3(22.5, 3.1, 8.5) };
}

export function buildMonuments({ scene, stonesGltf, creditCount }) {
  const sign = buildSignpost(scene);
  const crypt = buildCrypt(scene);

  // The supplied GLB holds one mesh per marker, so each credit gets a
  // visually distinct stone. If it is missing we fall back to plain slabs —
  // the credits are DOM labels, so the information survives regardless.
  const sources = [];
  if (stonesGltf) {
    stonesGltf.scene.traverse((o) => { if (o.isMesh) sources.push(o); });
  }

  const credits = [];
  const creditStones = [];
  const count = Math.min(creditCount, MONUMENT_SPOTS.length);
  for (let i = 0; i < count; i++) {
    const [x, z, rotY, s] = MONUMENT_SPOTS[i];
    const src = sources.length ? sources[i % sources.length].clone(true) : fallbackStone();
    const stone = standUpright(src, STONE_HEIGHT * s);
    stone.position.set(x, 0, z);
    stone.rotation.y = rotY;
    scene.add(stone);
    credits.push(new THREE.Vector3(x, STONE_HEIGHT * s + 0.45, z));

    // The song title is cut into the face of the stone, the same way the
    // signpost's words are: the canvas carries letterform alpha only and the
    // material colour is the ink, so a hover can light it without redrawing
    // anything. This replaces the floating HTML labels, which piled up on
    // top of each other along the row and read as web furniture stuck over
    // the world rather than part of it.
    const credit = CREDITS[i];
    if (credit) {
      const plate = new THREE.Mesh(
        new THREE.PlaneGeometry(0.78, 0.2),
        new THREE.MeshBasicMaterial({
          map: makeEngravedTexture(credit.track, { widthPx: 512, heightPx: 132, basePx: 62 }),
          transparent: true,
          color: ENGRAVED_INK,
          depthWrite: false,
        }),
      );
      // On the face of the stone, a little above its middle, standing just
      // proud of the surface so it never z-fights with the carving beneath.
      plate.position.set(0, STONE_HEIGHT * s * 0.66, 0.42);
      stone.add(plate);
      stone.userData.href = credit.url;
      stone.userData.label = `${credit.artist} — ${credit.track}`;
      stone.userData.textMesh = plate;
      creditStones.push(stone);
    }
  }

  return {
    anchors: { sign: sign.anchor, credits, crypt: crypt.anchor },
    signArms: sign.arms,
    creditStones,
  };
}
