import * as THREE from 'three';
import { positionAt } from './path.js';
import { makeEngravedTexture, ENGRAVED_STONE_INK } from './engraving.js';
import { CREDITS } from '../content/portfolio.js';

// Ten song stones flanking the church approach, alternating sides so the
// walk reads as an avenue. Deterministic — the clearance test below is only
// meaningful against fixed positions.
// Generated by sampling the road between t=0.12 and t=0.56 and stepping a
// perpendicular offset of ~4.6-5.4m alternately to each side, then measured
// at 4.60m clearance from the camera corridor.
export const MONUMENT_SPOTS = [
  [5.6, 39.93, 0.13, 1.0],
  [-3.46, 35.72, -0.44, 1.1],
  [7.18, 33.98, 0.23, 0.95],
  [-2.75, 30.97, -0.26, 1.05],
  [6.32, 26.81, 0.54, 1.0],
  [-4.45, 27.24, 0.06, 1.1],
  [3.86, 21.05, 0.67, 0.95],
  [-6.17, 21.24, -0.06, 1.05],
  [3.81, 17.82, 0.2, 1.0],
  [-5.16, 12.93, -0.66, 1.1],
];

function minDistanceToRoute(x, z) {
  let min = Infinity;
  for (let i = 0; i <= 300; i++) {
    const p = positionAt(i / 300);
    const d = Math.hypot(p.x - x, p.z - z);
    if (d < min) min = d;
  }
  return min;
}


// Smallest horizontal distance from any monument to the scenic route — the
// camera must not clip a headstone as it walks the row.
export function minWorkPathClearance() {
  return Math.min(...MONUMENT_SPOTS.map(([x, z]) => minDistanceToRoute(x, z)));
}


// Which side of the scenic route a point falls on: positive one way,
// negative the other. Used to prove the stones flank the walk.
export function sideOfRoute(x, z) {
  let bestT = 0;
  let bestD = Infinity;
  for (let i = 0; i <= 300; i++) {
    const t = i / 300;
    const p = positionAt(t);
    const d = Math.hypot(p.x - x, p.z - z);
    if (d < bestD) { bestD = d; bestT = t; }
  }
  const p = positionAt(bestT);
  // Finite-difference tangent — avoids exporting yet another curve accessor
  // from path.js for one geometric test.
  const ahead = positionAt(Math.min(bestT + 0.01, 1));
  const behind = positionAt(Math.max(bestT - 0.01, 0));
  const tx = ahead.x - behind.x;
  const tz = ahead.z - behind.z;
  return tx * (z - p.z) - tz * (x - p.x);
}

const STONE_HEIGHT = 1.35;

function fallbackStone() {
  const g = new THREE.Group();
  const mat = new THREE.MeshStandardMaterial({ color: '#3a3f3a', roughness: 1 });
  const slab = new THREE.Mesh(new THREE.BoxGeometry(0.8, STONE_HEIGHT, 0.2), mat);
  slab.position.y = STONE_HEIGHT / 2;
  g.add(slab);
  return g;
}

// Scale an object so it stands `height` tall with its feet on y = 0.
function standUpright(obj, height) {
  const box = new THREE.Box3().setFromObject(obj);
  const size = box.getSize(new THREE.Vector3());
  if (size.y > 0) obj.scale.multiplyScalar(height / size.y);
  const after = new THREE.Box3().setFromObject(obj);
  const centre = after.getCenter(new THREE.Vector3());
  obj.position.x -= centre.x;
  obj.position.z -= centre.z;
  obj.position.y -= after.min.y;
  const wrapper = new THREE.Group();
  wrapper.add(obj);
  return wrapper;
}

export function buildMonuments({ scene, stonesGltf, creditCount }) {

  // The supplied GLB holds one mesh per marker, so each credit gets a
  // visually distinct stone. If it is missing we fall back to plain slabs —
  // the credits are DOM labels, so the information survives regardless.
  const sources = [];
  if (stonesGltf) {
    stonesGltf.scene.traverse((o) => { if (o.isMesh) sources.push(o); });
  }

  const credits = [];
  const creditStones = [];
  const count = Math.min(creditCount, MONUMENT_SPOTS.length);
  for (let i = 0; i < count; i++) {
    const [x, z, rotY, s] = MONUMENT_SPOTS[i];
    const src = sources.length ? sources[i % sources.length].clone(true) : fallbackStone();
    const stone = standUpright(src, STONE_HEIGHT * s);
    stone.position.set(x, 0, z);
    stone.rotation.y = rotY;
    scene.add(stone);
    credits.push(new THREE.Vector3(x, STONE_HEIGHT * s + 0.45, z));

    // The song title is cut into the face of the stone, the same way the
    // signpost's words are: the canvas carries letterform alpha only and the
    // material colour is the ink, so a hover can light it without redrawing
    // anything. This replaces the floating HTML labels, which piled up on
    // top of each other along the row and read as web furniture stuck over
    // the world rather than part of it.
    const credit = CREDITS[i];
    if (credit) {
      // Size and place the plate from the stone's OWN bounding box. These
      // markers come from a set with quite different shapes and depths, so a
      // fixed offset either buries the words inside the stone or leaves them
      // hanging in the air beside it.
      const box = new THREE.Box3().setFromObject(stone);
      const size = box.getSize(new THREE.Vector3());
      // Wider than the stone: the words are what the visitor is here to
      // read, and at 3m off the road a stone-width plate was an
      // illegible smudge in every screenshot.
      const plateW = Math.max(1.5, size.x * 1.5);
      const plate = new THREE.Mesh(
        new THREE.PlaneGeometry(plateW, plateW * 0.3),
        new THREE.MeshBasicMaterial({
          map: makeEngravedTexture(credit.track, { widthPx: 768, heightPx: 200, basePx: 104 }),
          transparent: true,
          // Lighter than the signpost's ink: these are cut into pale
          // granite, not dark wood, and must carry at road distance.
          color: ENGRAVED_STONE_INK,
          depthWrite: false,
        }),
      );
      // On the face, above the middle, standing just proud of the surface so
      // it never z-fights with the stone behind it.
      plate.position.set(0, size.y * 0.66, size.z / 2 + 0.05);
      stone.add(plate);
      stone.userData.href = credit.url;
      stone.userData.label = `${credit.artist} — ${credit.track}`;
      stone.userData.textMesh = plate;
      creditStones.push(stone);
    }
  }

  return { creditStones };
}
